snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "(temp_f float)"
return_type = "float"
file = "app.zip"
name = "fahrenheit_to_celsius_udf"
handler = "app.main"
execute_as_caller = true

[dev]
database = "PL_HOL_DEV"
schema = "ANALYTICS"
warehouse = "DEV_HOL_WH"
role = "PL_DEV_HOL"
overwrite = true
